### ISSUE TITLE
opening collections when in combat causes error

### ISSUE THREAD

**Issue by JPEscher** [GurliGebis/WoWAddon-PokemonTrainerNG#16]
bug sack/bug grabber data:

reproduction steps (done using training dummy while trying to repro something for a diff mod)
1: go to training dummies in dornogal
2: enter combat
3: open collections

note: 2x is because i tested the keyboard shortcut, which also produced the error

```
2x [ADDON_ACTION_BLOCKED] AddOn 'PokemonTrainer' tried to call the protected function 'PTHealBandageFrameHealButton:SetAttribute()'.
[C]: ?

Locals:
(*temporary) = CollectionsMicroButton {
 FlashBorder = Texture {
 }
 QuickKeybindHighlightTexture = Texture {
 }
 lastNumMountsNeedingFanfare = 0
 tooltipText = "Warband Collections |cffffd200(SHIFT-P)|r"
 Background = Texture {
 }
 lastNumPetsNeedingFanfare = 0
 layoutIndex = 8
 textureName = "Collections"
 FlashContent = Texture {
 }
 PushedBackground = Texture {
 }
 commandName = "TOGGLECOLLECTIONS"
}
(*temporary) = "LeftButton"
(*temporary) = false
```

**Comment by JPEscher** [comment]
tried with just this enabled. got
```
Message: ...ner/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:3: attempt to index global 'LibStub' (a nil value)
Time: Thu Sep  4 06:32:05 2025
Count: 1
Stack:
[Interface/AddOns/Blizzard_UIParent/Shared/UIParent.lua]:221: in function 'UIParentLoadAddOn'
[Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua]:475: in function 'CollectionsJournal_LoadUI'
[Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua]:886: in function 'SetCollectionsJournalShown'
[Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua]:876: in function 'ToggleCollectionsJournal'
[TOGGLECOLLECTIONS]:1: in function <[string "TOGGLECOLLECTIONS"]:1>

Locals:
name = "Blizzard_Collections"
FailedAddOnLoad = <table> {
}
```
```
Message: ...ner/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:3: attempt to index global 'LibStub' (a nil value)
Time: Thu Sep  4 06:32:05 2025
Count: 1
Stack:
[Interface/AddOns/Blizzard_UIParent/Shared/UIParent.lua]:221: in function 'UIParentLoadAddOn'
[Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua]:475: in function 'CollectionsJournal_LoadUI'
[Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua]:886: in function 'SetCollectionsJournalShown'
[Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua]:876: in function 'ToggleCollectionsJournal'
[TOGGLECOLLECTIONS]:1: in function <[string "TOGGLECOLLECTIONS"]:1>

Locals:
name = "Blizzard_Collections"
FailedAddOnLoad = <table> {
}
```
```
Message: Interface/AddOns/PokemonTrainer/Libs/iLib/iLib.lua:7: Cannot find a library instance of "AceComm-3.0".
Time: Thu Sep  4 06:32:05 2025
Count: 1
Stack:
[Interface/AddOns/PokemonTrainer/Libs/LibStub/Libstub.lua]:23: in function 'LibStub'
[Interface/AddOns/PokemonTrainer/Libs/iLib/iLib.lua]:7: in main chunk
[C]: ?
[C]: in function 'LoadAddOn'
[Interface/AddOns/Blizzard_UIParent/Shared/UIParent.lua]:221: in function 'UIParentLoadAddOn'
[Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua]:475: in function 'CollectionsJournal_LoadUI'
[Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua]:886: in function 'SetCollectionsJournalShown'
[Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua]:876: in function 'ToggleCollectionsJournal'
[TOGGLECOLLECTIONS]:1: in function <[string "TOGGLECOLLECTIONS"]:1>

Locals:
self = <table> {
 minors = <table> {
 }
 minor = 2
 libs = <table> {
 }
}
major = "AceComm-3.0"
silent = nil
```
```
Message: ...Trainer/Libs/LibPetJournal-2.0/LibPetJournal-2.0.lua:44: Cannot find a library instance of "CallbackHandler-1.0".
Time: Thu Sep  4 06:32:05 2025
Count: 1
Stack:
[Interface/AddOns/PokemonTrainer/Libs/LibStub/Libstub.lua]:23: in function 'LibStub'
[Interface/AddOns/PokemonTrainer/Libs/LibPetJournal-2.0/LibPetJournal-2.0.lua]:44: in main chunk
[C]: ?
[C]: in function 'LoadAddOn'
[Interface/AddOns/Blizzard_UIParent/Shared/UIParent.lua]:221: in function 'UIParentLoadAddOn'
[Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua]:475: in function 'CollectionsJournal_LoadUI'
[Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua]:886: in function 'SetCollectionsJournalShown'
[Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua]:876: in function 'ToggleCollectionsJournal'
[TOGGLECOLLECTIONS]:1: in function <[string "TOGGLECOLLECTIONS"]:1>

Locals:
self = <table> {
 minors = <table> {
 }
 minor = 2
 libs = <table> {
 }
}
major = "CallbackHandler-1.0"
silent = nil
```

**Comment by GurliGebis** [comment]
I have pushed `11.2.0-20250904-1` with the remaining Ace3 libraries added - it should be available within the next hour - please try and update to that version, and see if it works by itself then.

**Comment by JPEscher** [comment]
<img width="655" height="670" alt="Image" src="https://github.com/user-attachments/assets/8e3e7180-ad23-470a-bcb8-41b50ebe877c" />

<img width="680" height="382" alt="Image" src="https://github.com/user-attachments/assets/e6a2ca16-989c-4afb-ac42-0ca56d064f06" />

<img width="589" height="402" alt="Image" src="https://github.com/user-attachments/assets/b99a12bc-fe47-423e-b8a3-fd433bf06d2c" />

<img width="794" height="417" alt="Image" src="https://github.com/user-attachments/assets/5352f23c-5586-4ef3-a367-ba5d7340b6b6" />

**Comment by JPEscher** [comment]
still getting it. but its also an edge case i dont think you should stress too much over.
